name: fp12
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-sitemap

# Includes an icon in the footer for each user name you enter
footer-links:
  github: fp12
  twitter: fp12gaming
