name: fp12
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

title: fp12's Tech blog
description: C++ / Python / Unreal Engine / Unity...

permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-sitemap

# Includes an icon in the footer for each user name you enter
footer-links:
  github: fp12

excerpt_separator: <!--more-->
theme: jekyll-theme-slate