name: fp12
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-sitemap

# Includes an icon in the footer for each user name you enter
footer-links:
  github: fp12
  twitter: fp12gaming

excerpt_separator: <!--more-->
theme: jekyll-theme-slate